-- QA Base schema and migrations. Run in Supabase SQL Editor.
-- Replace the owner email below before the first run.

create table if not exists public.access_members (
  id bigint generated by default as identity primary key,
  email text unique not null check (email = lower(email)),
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  section text not null default 'theory' check (section in ('theory', 'practice')),
  category text not null,
  title text not null,
  description text not null,
  content text not null,
  read_time text not null default '',
  color text not null default 'purple',
  icon text not null default '◉',
  image_url text,
  status text not null default 'published' check (status in ('draft', 'published')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.articles add column if not exists section text not null default 'theory';
alter table public.articles add column if not exists status text not null default 'published';
alter table public.articles add column if not exists sort_order integer not null default 0;
alter table public.articles add column if not exists updated_at timestamptz not null default now();
alter table public.articles drop constraint if exists articles_section_check;
alter table public.articles add constraint articles_section_check check (section in ('theory', 'practice'));
alter table public.articles drop constraint if exists articles_status_check;
alter table public.articles add constraint articles_status_check check (status in ('draft', 'published'));

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.article_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id bigint not null references public.articles(id) on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (user_id, article_id)
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  correct_option integer not null default 0,
  explanation text not null default '',
  sort_order integer not null default 0
);

insert into public.access_members (email, is_admin)
values ('tuman199654@gmail.com', true)
on conflict (email) do update set is_admin = true;

insert into public.articles (category, title, description, content, read_time, color, icon, sort_order)
select seed.category, seed.title, seed.description, seed.content, seed.read_time, seed.color, seed.icon, seed.sort_order
from (values
  ('Основы', 'Что такое тестирование?', 'Цели, принципы и место QA в разработке продукта.', '<h3>Зачем нужно тестирование</h3><p>Тестирование — это исследование продукта с целью получить информацию о его качестве и снизить риски для пользователя и бизнеса.</p><h3>Главная мысль</h3><p>QA — не только поиск багов. Хороший специалист помогает команде предотвращать проблемы, задавая правильные вопросы ещё до написания кода.</p>', '8 мин', 'purple', '◉', 10),
  ('Основы', 'Виды тестирования', 'Функциональное, нефункциональное, регрессионное и другие виды.', '<h3>Функциональное тестирование</h3><p>Проверяет, что система делает именно то, что заявлено в требованиях.</p><h3>Нефункциональное тестирование</h3><p>Оценивает производительность, безопасность, удобство использования и совместимость.</p>', '12 мин', 'yellow', '▤', 20),
  ('Тест-дизайн', 'Техники тест-дизайна', 'Как получать максимум проверок, затрачивая минимум времени.', '<h3>Базовые техники</h3><p>Классы эквивалентности, анализ граничных значений, таблицы решений и диаграммы состояний помогают системно выбирать тестовые данные.</p>', '15 мин', 'blue', '⌘', 30),
  ('Документация', 'Баг-репорт без воды', 'Структура понятного отчёта, который разработчик захочет исправить.', '<h3>Хорошая структура</h3><p>Заголовок, окружение, предусловия, шаги воспроизведения, фактический и ожидаемый результат, серьёзность и вложения.</p>', '10 мин', 'pink', '!', 40),
  ('API', 'Основы API-тестирования', 'Запросы, ответы, коды состояния и проверки контрактов.', '<h3>На что смотреть</h3><p>Проверяйте метод и URL, статус-код, заголовки, структуру и значения тела ответа, а также время выполнения.</p>', '18 мин', 'green', '↔', 50),
  ('Процессы', 'Жизненный цикл бага', 'От обнаружения до закрытия: статусы и коммуникация команды.', '<h3>Типичный путь</h3><p>Новый → Открыт → В работе → Исправлен → На проверке → Закрыт.</p>', '9 мин', 'orange', '↻', 60)
) as seed(category, title, description, content, read_time, color, icon, sort_order)
where not exists (select 1 from public.articles existing where existing.title = seed.title);

insert into public.articles (section, category, title, description, content, read_time, color, icon, sort_order)
select 'practice', 'Практические задания Manual QA тестирования', 'Практика: тестирование формы входа',
  'Проверьте позитивные и негативные сценарии для формы авторизации.',
  '<h3>Задание</h3><p>Составьте набор проверок для формы входа: валидные данные, неверный пароль, пустые поля, формат email и блокировка после повторных попыток.</p><h3>Результат</h3><p>Оформите тест-кейсы и заведите баг-репорт для найденных проблем.</p>',
  '20 мин', 'blue', '✓', 10
where not exists (select 1 from public.articles where title = 'Практика: тестирование формы входа');

insert into public.quiz_questions (article_id, question, options, correct_option, explanation, sort_order)
select a.id, 'Что является главной целью тестирования?', '["Найти все возможные баги","Получить информацию о качестве и снизить риски","Проверить только UI"]'::jsonb, 1, 'Тестирование помогает принимать решения о качестве и рисках продукта.', 10
from public.articles a
where a.title = 'Что такое тестирование?'
  and not exists (select 1 from public.quiz_questions q where q.article_id = a.id);

insert into public.quiz_questions (article_id, question, options, correct_option, explanation, sort_order)
select a.id, 'Что проверяет функциональное тестирование?', '["Заявленное поведение системы","Только скорость ответа","Только внешний вид"]'::jsonb, 0, 'Функциональные проверки сопоставляют поведение системы с требованиями.', 10
from public.articles a
where a.title = 'Виды тестирования'
  and not exists (select 1 from public.quiz_questions q where q.article_id = a.id);

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public
as $$ select exists (select 1 from public.access_members where email = lower(auth.email()) and is_admin); $$;

create or replace function public.has_access()
returns boolean language sql security definer set search_path = public
as $$ select exists (select 1 from public.access_members where email = lower(auth.email())); $$;

alter table public.access_members enable row level security;
alter table public.articles enable row level security;
alter table public.profiles enable row level security;
alter table public.article_progress enable row level security;
alter table public.quiz_questions enable row level security;

drop policy if exists "members can read own access" on public.access_members;
create policy "members can read own access" on public.access_members for select to authenticated
using (email = lower(auth.email()) or public.is_admin());
drop policy if exists "admins manage members" on public.access_members;
create policy "admins manage members" on public.access_members for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "members read articles" on public.articles;
create policy "members read articles" on public.articles for select to authenticated
using (public.is_admin() or (public.has_access() and status = 'published'));
drop policy if exists "admins manage articles" on public.articles;
create policy "admins manage articles" on public.articles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users manage own profile" on public.profiles;
create policy "users manage own profile" on public.profiles for all to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists "users manage own progress" on public.article_progress;
create policy "users manage own progress" on public.article_progress for all to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "members read quizzes" on public.quiz_questions;
create policy "members read quizzes" on public.quiz_questions for select to authenticated
using (public.is_admin() or public.has_access());
drop policy if exists "admins manage quizzes" on public.quiz_questions;
create policy "admins manage quizzes" on public.quiz_questions for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Public URLs are safe because writes are restricted to admins / the owner.
insert into storage.buckets (id, name, public)
values ('article-images', 'article-images', true), ('avatars', 'avatars', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "public can view QA Base images" on storage.objects;
create policy "public can view QA Base images" on storage.objects for select
using (bucket_id in ('article-images', 'avatars'));
drop policy if exists "admins upload article images" on storage.objects;
create policy "admins upload article images" on storage.objects for insert to authenticated
with check (bucket_id = 'article-images' and public.is_admin());
drop policy if exists "admins update article images" on storage.objects;
create policy "admins update article images" on storage.objects for update to authenticated
using (bucket_id = 'article-images' and public.is_admin());
drop policy if exists "admins delete article images" on storage.objects;
create policy "admins delete article images" on storage.objects for delete to authenticated
using (bucket_id = 'article-images' and public.is_admin());
drop policy if exists "users upload own avatar" on storage.objects;
create policy "users upload own avatar" on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "users update own avatar" on storage.objects;
create policy "users update own avatar" on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
