-- QA Base schema and migrations. Run in Supabase SQL Editor.
-- Replace the owner email below before the first run.

create table if not exists public.access_members (
  id bigint generated by default as identity primary key,
  email text unique not null check (email = lower(email)),
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  section text not null default 'theory' check (section in ('theory', 'practice')),
  category text not null,
  title text not null,
  description text not null,
  content text not null,
  read_time text not null default '',
  color text not null default 'purple',
  icon text not null default '◉',
  image_url text,
  status text not null default 'published' check (status in ('draft', 'published')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.articles add column if not exists section text not null default 'theory';
alter table public.articles add column if not exists status text not null default 'published';
alter table public.articles add column if not exists sort_order integer not null default 0;
alter table public.articles add column if not exists updated_at timestamptz not null default now();
alter table public.articles drop constraint if exists articles_section_check;
alter table public.articles add constraint articles_section_check check (section in ('theory', 'practice'));
alter table public.articles drop constraint if exists articles_status_check;
alter table public.articles add constraint articles_status_check check (status in ('draft', 'published'));

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.article_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id bigint not null references public.articles(id) on delete cascade,
  completed_at timestamptz not null default now(),
  primary key (user_id, article_id)
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  correct_option integer not null default 0,
  explanation text not null default '',
  sort_order integer not null default 0
);

insert into public.access_members (email, is_admin)
values ('tuman199654@gmail.com', true)
on conflict (email) do update set is_admin = true;

insert into public.articles (section, category, title, description, content, read_time, color, icon, sort_order)
select seed.section, seed.category, seed.title, seed.description, seed.content, seed.read_time, seed.color, seed.icon, seed.sort_order
from (values
  ('theory', 'Основы', 'Тестирование: определение, цели и принципы',
    'Что именно проверяет тестировщик, зачем это нужно бизнесу и почему тестирование не доказывает отсутствие дефектов.',
    '<h3>Определение</h3><p><strong>Тестирование</strong> — это исследование продукта и его документации, во время которого команда получает информацию о качестве и рисках. Тестировщик сравнивает фактическое поведение с ожиданиями, но не может доказать, что дефектов совсем нет.</p><h3>Цели</h3><ul><li>найти проблемы до того, как они затронут пользователя;</li><li>дать команде проверяемую информацию для решения о релизе;</li><li>снизить риски потери денег, данных и доверия пользователей;</li><li>проверить, что продукт решает задачу, а не только работает без ошибок.</li></ul><h3>Принципы</h3><p>Тестирование показывает наличие дефектов, а не их отсутствие. Проверить всё невозможно, поэтому проверки выбирают по риску. Чем раньше команда тестирует требования и дизайн, тем дешевле исправление. Дефекты распределяются неравномерно, а повтор одних и тех же проверок со временем теряет эффективность. Контекст важен: для банковского платежа и для игры нужны разные глубина и виды тестов.</p><h3>Пример</h3><p>Для интернет-магазина важно проверить не только кнопку <em>Оплатить</em>, но и списание ровно один раз, возврат после ошибки банка и понятное сообщение пользователю.</p>',
    '10 мин', 'purple', '◉', 10),
  ('theory', 'Виды тестирования', 'Виды тестирования: что и когда проверять',
    'Функциональные и нефункциональные проверки, уровни тестирования и разница между smoke, regression и exploratory.',
    '<h3>Функциональные проверки</h3><p>Проверяют, что система делает то, что описано в требованиях: например, корректный пароль открывает личный кабинет, а неверный не открывает его.</p><h3>Нефункциональные проверки</h3><p>Оценивают характеристики системы: скорость, безопасность, доступность, удобство, совместимость и устойчивость к нагрузке.</p><h3>Уровни</h3><ul><li><strong>Unit</strong> — отдельная функция или класс;</li><li><strong>Integration</strong> — взаимодействие модулей, например API и базы;</li><li><strong>System</strong> — продукт целиком;</li><li><strong>Acceptance</strong> — пригодность решения для пользователя или бизнеса.</li></ul><h3>Частые термины</h3><p><strong>Smoke</strong> — короткий набор критических проверок после сборки. <strong>Regression</strong> — повторная проверка уже работавших возможностей после изменений. <strong>Retest</strong> — проверка конкретного исправленного дефекта. <strong>Exploratory</strong> — одновременное изучение продукта, проектирование и выполнение проверок.</p><h3>Пример</h3><p>После изменения корзины smoke проверит вход, добавление товара и оформление заказа. Полная регрессия дополнительно проверит промокоды, возвраты, мобильный экран и письма.</p>',
    '14 мин', 'yellow', '▤', 20),
  ('theory', 'Тест-дизайн', 'Техники тест-дизайна: как выбирать проверки',
    'Практический набор техник, который помогает покрыть важные варианты без бесконечного количества тестов.',
    '<h3>Классы эквивалентности</h3><p>Разделите входы на группы, внутри которых программа должна вести себя одинаково. Для поля возраста от 18 до 65 достаточно взять представителя валидного класса, например 30, и представителей невалидных классов 17 и 66.</p><h3>Граничные значения</h3><p>Ошибки часто находятся на границе, поэтому для диапазона 18–65 проверьте 17, 18, 19, 64, 65 и 66.</p><h3>Таблица решений</h3><p>Перечислите условия и ожидаемые действия. Для скидки можно отдельно проверить наличие промокода, минимальную сумму заказа и статус клиента, включая конфликт условий.</p><h3>Переходы состояний</h3><p>Опишите состояния и разрешённые переходы. Заказ может пройти путь <code>Новый → Оплачен → Отправлен → Доставлен</code>, но после доставки нельзя вернуть его в состояние Новый.</p><h3>Попарное тестирование и чек-листы</h3><p>Когда вариантов слишком много, попарный подход покрывает все пары значений параметров. Чек-лист помогает не забыть важные области, а не заменяет анализ риска.</p>',
    '16 мин', 'blue', '⌘', 30),
  ('theory', 'Пирамида тестов', 'Пирамида тестирования',
    'Как распределять автоматические и ручные проверки, чтобы получать быструю обратную связь по разумной цене.',
    '<h3>Три уровня</h3><p>В основании находятся многочисленные быстрые <strong>unit-тесты</strong>. Выше — меньшее число <strong>интеграционных и API-тестов</strong>, проверяющих связи между компонентами. На вершине — небольшое количество медленных сквозных UI-тестов и ручных сценариев.</p><h3>Почему форма пирамиды полезна</h3><p>Нижние проверки запускаются часто, изолированы и быстро показывают место проблемы. Сквозные проверки ближе к реальному сценарию, но дороже в поддержке и чаще бывают нестабильными. Поэтому тестов верхнего уровня должно быть ровно столько, сколько нужно для критических пользовательских путей.</p><h3>Пример</h3><p>Для расчёта доставки можно иметь десятки unit-тестов тарифной формулы, несколько API-тестов контракта и один UI-тест оформления заказа. Это лучше, чем проверять каждую комбинацию только через браузер.</p><p>Пирамида — не закон: мобильное приложение, устройство или продукт с малым количеством логики могут потребовать другой пропорции. Главное — быстрый сигнал и подходящее покрытие риска.</p>',
    '9 мин', 'green', '△', 40),
  ('theory', 'Документация', 'Тестовая документация: от чек-листа до отчёта',
    'Какие записи помогают планировать проверки, повторять результаты и принимать решение о качестве.',
    '<h3>Основные артефакты</h3><ul><li><strong>Тест-план</strong> фиксирует область, риски, виды проверок, окружение и критерии входа и выхода;</li><li><strong>Тест-кейс</strong> содержит предусловия, шаги, данные и ожидаемый результат;</li><li><strong>Чек-лист</strong> кратко перечисляет области проверки и удобен для быстрых повторных проходов;</li><li><strong>Отчёт о тестировании</strong> показывает, что проверено, какие риски остались и можно ли выпускать версию.</li></ul><h3>Хороший баг-репорт</h3><p>Укажите однозначный заголовок, версию и окружение, предусловия, минимальные шаги, фактический и ожидаемый результат, частоту воспроизведения и вложения. Один отчёт — одна проблема.</p><h3>Пример</h3><p><strong>Заголовок:</strong> «Кнопка Сохранить неактивна после ввода валидного телефона на Android 14». В шагах укажите тестовый аккаунт без секретных данных, браузер Chrome 126, фактическое состояние и ожидаемое сохранение профиля.</p><p>Не добавляйте в отчёт пароли, токены или персональные данные. Документация должна помогать воспроизведению, а не превращаться в стену текста.</p>',
    '12 мин', 'pink', '!', 50),
  ('theory', 'Дефекты', 'Приоритет и серьёзность дефекта',
    'Как отличать влияние ошибки от срочности исправления и не путать severity с priority.',
    '<h3>Серьёзность (severity)</h3><p>Это степень влияния дефекта на систему и пользователя. Blocker не даёт тестировать или выпускать продукт, Critical ломает ключевой сценарий или приводит к потере данных, Major нарушает важную функцию, Minor затрудняет работу, а Trivial обычно касается текста или косметики.</p><h3>Приоритет (priority)</h3><p>Это очередность исправления с учётом сроков, риска, аудитории и целей бизнеса. Приоритет может быть высоким даже у небольшой ошибки, если завтра стартует рекламная кампания.</p><h3>Матрица примеров</h3><table><thead><tr><th>Дефект</th><th>Серьёзность</th><th>Приоритет</th></tr></thead><tbody><tr><td>Оплата падает у всех клиентов</td><td>Critical</td><td>High</td></tr><tr><td>Опечатка в заголовке главной страницы</td><td>Trivial</td><td>High перед рекламной кампанией</td></tr><tr><td>Редкая ошибка в отчёте для внутреннего пользователя</td><td>Major</td><td>Low</td></tr></tbody></table><h3>Правило</h3><p>Тестировщик предлагает оценку и объясняет риск, но окончательный приоритет согласует команда с владельцем продукта. В отчёте приводите факты: затронутых пользователей, частоту и последствия.</p>',
    '11 мин', 'orange', '!', 60),
  ('theory', 'Методологии', 'Методологии разработки и роль QA',
    'Чем отличаются Waterfall, Agile, Scrum и Kanban и как тестирование встраивается в каждый процесс.',
    '<h3>Waterfall</h3><p>Этапы идут последовательно: требования, разработка, тестирование и релиз. Тестировщик подключается рано к анализу требований, иначе ошибки обнаружатся поздно и будут дорогими.</p><h3>Agile</h3><p>Agile — это набор ценностей и принципов коротких итераций, обратной связи и готовности менять план. Тестирование выполняется непрерывно, а качество является ответственностью всей команды.</p><h3>Scrum</h3><p>Scrum использует спринты, Product Backlog, планирование, Daily Scrum, Review и Retrospective. QA помогает уточнять критерии приёмки, оценивает риски, тестирует историю в спринте и не считает её готовой без нужного уровня качества.</p><h3>Kanban</h3><p>Kanban визуализирует поток задач и ограничивает незавершённую работу. Тестировщик следит, чтобы колонка проверки не стала очередью, и помогает команде уменьшать время прохождения задачи.</p><h3>Пример</h3><p>Для истории «пользователь меняет email» команда заранее договаривается о критериях: письмо подтверждения, запрет занятого адреса, повторная отправка и безопасный выход из старого аккаунта. QA проверяет их в той же итерации, а не после общего релиза.</p>',
    '13 мин', 'purple', '↻', 70)
) as seed(section, category, title, description, content, read_time, color, icon, sort_order)
where not exists (
  select 1 from public.articles existing
  where existing.section = seed.section and existing.title = seed.title
);

insert into public.articles (section, category, title, description, content, read_time, color, icon, sort_order)
select seed.section, seed.category, seed.title, seed.description, seed.content, seed.read_time, seed.color, seed.icon, seed.sort_order
from (values
  ('practice', 'Практические задания Manual QA тестирования', 'Практика: тестирование формы входа',
    'Проверьте позитивные и негативные сценарии для формы авторизации.',
    '<h3>Задание</h3><p>Составьте набор проверок для формы входа: валидные данные, неверный пароль, пустые поля, формат email и блокировка после повторных попыток.</p><h3>Реалистичный пример</h3><p>Проверьте, что пользователь с email <code>qa@example.com</code> входит с правильным паролем, а неверный пароль не раскрывает, существует ли такой аккаунт. После пяти неудачных попыток проверьте задержку или блокировку согласно требованиям.</p><h3>Результат</h3><p>Оформите тест-кейсы, приложите данные окружения и заведите отдельный баг-репорт для каждой найденной проблемы.</p>',
    '20 мин', 'blue', '✓', 10)
) as seed(section, category, title, description, content, read_time, color, icon, sort_order)
where not exists (
  select 1 from public.articles existing
  where existing.section = seed.section and existing.title = seed.title
);

insert into public.quiz_questions (article_id, question, options, correct_option, explanation, sort_order)
select a.id, 'Что является главной целью тестирования?', '["Найти все возможные баги","Получить информацию о качестве и снизить риски","Проверить только UI"]'::jsonb, 1, 'Тестирование помогает принимать решения о качестве и рисках продукта.', 10
from public.articles a
where a.title = 'Что такое тестирование?'
  and not exists (select 1 from public.quiz_questions q where q.article_id = a.id);

insert into public.quiz_questions (article_id, question, options, correct_option, explanation, sort_order)
select a.id, 'Что проверяет функциональное тестирование?', '["Заявленное поведение системы","Только скорость ответа","Только внешний вид"]'::jsonb, 0, 'Функциональные проверки сопоставляют поведение системы с требованиями.', 10
from public.articles a
where a.title = 'Виды тестирования'
  and not exists (select 1 from public.quiz_questions q where q.article_id = a.id);

insert into public.quiz_questions (article_id, question, options, correct_option, explanation, sort_order)
select a.id, 'Что является главной целью тестирования?', '["Доказать отсутствие всех дефектов","Получить информацию о качестве и снизить риски","Проверить только код разработчика"]'::jsonb, 1, 'Тестирование даёт команде информацию для решений и помогает управлять рисками.', 10
from public.articles a
where a.title = 'Тестирование: определение, цели и принципы'
  and not exists (select 1 from public.quiz_questions q where q.article_id = a.id);

insert into public.quiz_questions (article_id, question, options, correct_option, explanation, sort_order)
select a.id, 'Какие значения полезны для диапазона от 18 до 65?', '["Только 18 и 65","17, 18, 19, 64, 65 и 66","Только 30"]'::jsonb, 1, 'Граничные значения включают сами границы, соседей и представителей классов.', 10
from public.articles a
where a.title = 'Техники тест-дизайна: как выбирать проверки'
  and not exists (select 1 from public.quiz_questions q where q.article_id = a.id);

insert into public.quiz_questions (article_id, question, options, correct_option, explanation, sort_order)
select a.id, 'Что означает priority в баг-репорте?', '["Влияние дефекта на систему","Очередность исправления с учётом бизнеса и рисков","Количество шагов воспроизведения"]'::jsonb, 1, 'Priority показывает срочность и порядок работы, а severity — влияние дефекта.', 10
from public.articles a
where a.title = 'Приоритет и серьёзность дефекта'
  and not exists (select 1 from public.quiz_questions q where q.article_id = a.id);

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public
as $$ select exists (select 1 from public.access_members where email = lower(auth.email()) and is_admin); $$;

create or replace function public.has_access()
returns boolean language sql security definer set search_path = public
as $$ select exists (select 1 from public.access_members where email = lower(auth.email())); $$;

alter table public.access_members enable row level security;
alter table public.articles enable row level security;
alter table public.profiles enable row level security;
alter table public.article_progress enable row level security;
alter table public.quiz_questions enable row level security;

drop policy if exists "members can read own access" on public.access_members;
create policy "members can read own access" on public.access_members for select to authenticated
using (email = lower(auth.email()) or public.is_admin());
drop policy if exists "admins manage members" on public.access_members;
create policy "admins manage members" on public.access_members for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "members read articles" on public.articles;
create policy "members read articles" on public.articles for select to authenticated
using (public.is_admin() or (public.has_access() and status = 'published'));
drop policy if exists "admins manage articles" on public.articles;
create policy "admins manage articles" on public.articles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users manage own profile" on public.profiles;
create policy "users manage own profile" on public.profiles for all to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists "users manage own progress" on public.article_progress;
create policy "users manage own progress" on public.article_progress for all to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "members read quizzes" on public.quiz_questions;
create policy "members read quizzes" on public.quiz_questions for select to authenticated
using (public.is_admin() or public.has_access());
drop policy if exists "admins manage quizzes" on public.quiz_questions;
create policy "admins manage quizzes" on public.quiz_questions for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Public URLs are safe because writes are restricted to admins / the owner.
insert into storage.buckets (id, name, public)
values ('article-images', 'article-images', true), ('avatars', 'avatars', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "public can view QA Base images" on storage.objects;
create policy "public can view QA Base images" on storage.objects for select
using (bucket_id in ('article-images', 'avatars'));
drop policy if exists "admins upload article images" on storage.objects;
create policy "admins upload article images" on storage.objects for insert to authenticated
with check (bucket_id = 'article-images' and public.is_admin());
drop policy if exists "admins update article images" on storage.objects;
create policy "admins update article images" on storage.objects for update to authenticated
using (bucket_id = 'article-images' and public.is_admin());
drop policy if exists "admins delete article images" on storage.objects;
create policy "admins delete article images" on storage.objects for delete to authenticated
using (bucket_id = 'article-images' and public.is_admin());
drop policy if exists "users upload own avatar" on storage.objects;
create policy "users upload own avatar" on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "users update own avatar" on storage.objects;
create policy "users update own avatar" on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
